<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
       	<title>SON Delivery</title>
        <link href='http://fonts.googleapis.com/css?family=Ubuntu:regular,italic,bold,bolditalic' rel='stylesheet' type='text/css' />
        <link type="text/css" href="<?php echo $this->baseUrl("style/css.css"); ?>" rel="StyleSheet" />
        <link type="text/css" href="<?php echo $this->baseUrl("style/form.css"); ?>" rel="StyleSheet" />
        
        <script type="text/javascript">
            var BASEURL = "<?php echo $this->baseUrl("/"); ?>";
        </script>
        <?php echo $this->jQuery()->enable(); ?>
        <?php
        echo $this->headScript()
                ->appendFile('/scripts/Pedido.js', 'text/javascript');
        ?>
        
    </head>
    <body>
        <div id="geral">
            <div id="topo">
                <h1>SON Delivery - Administração</h1>
                <ul class="navigation" id="menu">
                    <li><a href="<?php echo $this->url(array('controller' => 'index', 'module' => 'admin'), null, 1); ?>">Produtos</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'pedidos', 'module' => 'admin'), null, 1); ?>">Pedidos</a></li>
                    <?php if (Zend_Auth::getInstance()->setStorage(new Zend_Auth_Storage_Session("admin"))->hasIdentity()): ?>
                        <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'module' => 'admin'), null, 1); ?>">Logout</a></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->url(array('controller' => 'auth', 'module' => 'admin'), null, 1); ?>">Login</a></li>
                    <?php endif; ?>
                </ul>
            </div>
            <div id="meio">
                <div id="conteudo">
                    <?php echo $this->Layout()->content; ?>
                </div>

            </div>
            <div id="rodape">
                <div id="rodape-info">
                    SON Delivery - Todos os direitos reservados.
                </div>
            </div>
        </div>
    </body>
</html>
