<h2>Produtos</h2>

<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'new'), null, 1); ?>">Novo</a>
<br />
<br />

<table class="grid"  cellpadding="0" cellspacing="0" style="width:750px;">
    <thead>
        <tr>
            <td>ID</td>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Valor</td>
            <td>Ação</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->produtos as $produto): ?>
        <tr>
            <td><?=$produto['id']; ?></td>
            <td><?=$produto['nome']; ?></td>
            <td><?=$produto['descricao']; ?></td>
            <td><?=$produto['valor']; ?></td>
            <td>
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'edit', 'id' =>$produto['id']), null, 1); ?>">
                    Editar
                </a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>