<div id="listagem-pedidos">
    <h2>Pedidos</h2>

    <table class="grid" cellpadding="0" cellspacing="0" style="width:650px;">
        <thead>
            <tr>
                <td>Código</td>
                <td>Valor</td>
                <td>Ação</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pedidos as $pedido): ?>
                <tr>
                    <td><?= str_pad($pedido['id'], 5, STR_PAD_LEFT); ?></td>
                    <td>R$<?= number_format($pedido['total'],2,",","."); ?></td>
                    <td>
                        <a class="open-pedido" href="#" rel="<?= $pedido['id']; ?>">
                            Abrir pedido
                        </a>
                    </td>
                </tr>
                <tr>
                    <td colspan="3" id="pedido-detail-<?= $pedido['id']; ?>" style="display:none;"></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="clearfix"></div>